In [1]:
import pandas as pd
import string
import numpy as np
import nltk
import re

from sklearn.feature_extraction.text import CountVectorizer
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import MultinomialNB
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfTransformer
from sklearn import model_selection
from sklearn.utils.multiclass import unique_labels
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import LabelBinarizer
from sklearn.preprocessing import OrdinalEncoder


#hasil
from sklearn.metrics import recall_score, accuracy_score, classification_report
from sklearn.metrics import precision_score
from sklearn.metrics import f1_score
import seaborn as sns
import matplotlib.pyplot as plt



In [2]:
df_latih = pd.read_excel(r'D:\big data\Data Latih BDC.xlsx')

In [3]:

df_latih.tail()

ID  label              tanggal  \
4226  999287      1  2016-01-17 00:00:00   
4227  999472      1  2020-08-20 00:00:00   
4228  999501      1  2020-08-17 00:00:00   
4229  999848      1  2020-07-21 00:00:00   
4230  999860      1  2020-07-20 00:00:00   

                                                  judul  \
4226  : KPK Dilarang Membawa Brimob Bersenjata Masuk...   
4227            Foto pejabat keuangan dibawah palu arit   
4228  Gambar Denny Siregar Musuh Warga Tasikmalaya d...   
4229  Kaesang: Bapak Saya dengan Kesederhaan Bisa Ni...   
4230  Laser dari termometer gun akan merusak struktu...   

                                                 narasi nama file gambar  
4226  KPK Dilarang Membawa Brimob Bersenjata Masuk G...       999287.jpg  
4227  Jangan mau dialihkan kepada pakaian adat… FOKU...       999472.png  
4228                 Akhir nya bisa terkenal bang denny       999501.jpg  
4229  Bapak Saya dengan Kesederhaan Bisa Nipu Rakyat...       999848.jpg  
4230  IN: Saya nolak. Kalau Anda mau periksa, bukan ...       999860.png

In [4]:
df_latih = df_latih.drop("tanggal", axis=1)
df_latih = df_latih.drop("nama file gambar", axis=1)
df_latih = df_latih.drop("ID", axis=1)
df_latih

label                                              judul  \
0         1  Pemakaian Masker Menyebabkan Penyakit Legionna...   
1         1  Instruksi Gubernur Jateng tentang penilangan  ...   
2         1  Foto Jim Rohn: Jokowi adalah presiden terbaik ...   
3         1  ini bukan politik, tapi kenyataan Pak Jokowi b...   
4         1       Foto Kadrun kalo lihat foto ini panas dingin   
...     ...                                                ...   
4226      1  : KPK Dilarang Membawa Brimob Bersenjata Masuk...   
4227      1            Foto pejabat keuangan dibawah palu arit   
4228      1  Gambar Denny Siregar Musuh Warga Tasikmalaya d...   
4229      1  Kaesang: Bapak Saya dengan Kesederhaan Bisa Ni...   
4230      1  Laser dari termometer gun akan merusak struktu...   

                                                 narasi  
0     A caller to a radio talk show recently shared ...  
1     Yth.Seluruh Anggota Grup Sesuai Instruksi Gube...  
2     Jokowi adalah presiden terbaik dlm sejarah ban...  
3     Maaf Mas2 dan Mbak2, ini bukan politik, tapi k...  
4           Kadrun kalo lihat foto ini panas dingin . .  
...                                                 ...  
4226  KPK Dilarang Membawa Brimob Bersenjata Masuk G...  
4227  Jangan mau dialihkan kepada pakaian adat… FOKU...  
4228                 Akhir nya bisa terkenal bang denny  
4229  Bapak Saya dengan Kesederhaan Bisa Nipu Rakyat...  
4230  IN: Saya nolak. Kalau Anda mau periksa, bukan ...  

[4231 rows x 3 columns]

In [5]:
from nltk.corpus import stopwords 
#stopwords_indonesia = stopwords.words('indonesian')

In [6]:
df_latih

label                                              judul  \
0         1  Pemakaian Masker Menyebabkan Penyakit Legionna...   
1         1  Instruksi Gubernur Jateng tentang penilangan  ...   
2         1  Foto Jim Rohn: Jokowi adalah presiden terbaik ...   
3         1  ini bukan politik, tapi kenyataan Pak Jokowi b...   
4         1       Foto Kadrun kalo lihat foto ini panas dingin   
...     ...                                                ...   
4226      1  : KPK Dilarang Membawa Brimob Bersenjata Masuk...   
4227      1            Foto pejabat keuangan dibawah palu arit   
4228      1  Gambar Denny Siregar Musuh Warga Tasikmalaya d...   
4229      1  Kaesang: Bapak Saya dengan Kesederhaan Bisa Ni...   
4230      1  Laser dari termometer gun akan merusak struktu...   

                                                 narasi  
0     A caller to a radio talk show recently shared ...  
1     Yth.Seluruh Anggota Grup Sesuai Instruksi Gube...  
2     Jokowi adalah presiden terbaik dlm sejarah ban...  
3     Maaf Mas2 dan Mbak2, ini bukan politik, tapi k...  
4           Kadrun kalo lihat foto ini panas dingin . .  
...                                                 ...  
4226  KPK Dilarang Membawa Brimob Bersenjata Masuk G...  
4227  Jangan mau dialihkan kepada pakaian adat… FOKU...  
4228                 Akhir nya bisa terkenal bang denny  
4229  Bapak Saya dengan Kesederhaan Bisa Nipu Rakyat...  
4230  IN: Saya nolak. Kalau Anda mau periksa, bukan ...  

[4231 rows x 3 columns]

In [7]:
df_latih.sort_inplace=True

In [8]:
Ylatih = df_latih['label']
print(Ylatih)

0       1
1       1
2       1
3       1
4       1
       ..
4226    1
4227    1
4228    1
4229    1
4230    1
Name: label, Length: 4231, dtype: int64


In [9]:
encoder = LabelBinarizer()
Y = encoder.fit_transform(Ylatih)
print(Y)

[[1]
 [1]
 [1]
 ...
 [1]
 [1]
 [1]]


In [10]:
Xlatih = df_latih.drop("label", axis=1)
print(Xlatih)

                                                  judul  \
0     Pemakaian Masker Menyebabkan Penyakit Legionna...   
1     Instruksi Gubernur Jateng tentang penilangan  ...   
2     Foto Jim Rohn: Jokowi adalah presiden terbaik ...   
3     ini bukan politik, tapi kenyataan Pak Jokowi b...   
4          Foto Kadrun kalo lihat foto ini panas dingin   
...                                                 ...   
4226  : KPK Dilarang Membawa Brimob Bersenjata Masuk...   
4227            Foto pejabat keuangan dibawah palu arit   
4228  Gambar Denny Siregar Musuh Warga Tasikmalaya d...   
4229  Kaesang: Bapak Saya dengan Kesederhaan Bisa Ni...   
4230  Laser dari termometer gun akan merusak struktu...   

                                                 narasi  
0     A caller to a radio talk show recently shared ...  
1     Yth.Seluruh Anggota Grup Sesuai Instruksi Gube...  
2     Jokowi adalah presiden terbaik dlm sejarah ban...  
3     Maaf Mas2 dan Mbak2, ini bukan politik, tapi k...  
4

In [11]:
tfidf_transformer = OneHotEncoder()
X = tfidf_transformer.fit_transform(Xlatih)
print(X)
print(X.shape)

  (0, 2613)	1.0
  (0, 4339)	1.0
  (1, 1532)	1.0
  (1, 8053)	1.0
  (2, 1075)	1.0
  (2, 5938)	1.0
  (3, 4130)	1.0
  (3, 6395)	1.0
  (4, 1090)	1.0
  (4, 6019)	1.0
  (5, 4118)	1.0
  (5, 8195)	1.0
  (6, 2119)	1.0
  (6, 6302)	1.0
  (7, 1150)	1.0
  (7, 5834)	1.0
  (8, 1779)	1.0
  (8, 7036)	1.0
  (9, 3883)	1.0
  (9, 7035)	1.0
  (10, 317)	1.0
  (10, 4447)	1.0
  (11, 1477)	1.0
  (11, 4788)	1.0
  (12, 876)	1.0
  :	:
  (4218, 6301)	1.0
  (4219, 2427)	1.0
  (4219, 6706)	1.0
  (4220, 2259)	1.0
  (4220, 4904)	1.0
  (4221, 1797)	1.0
  (4221, 6095)	1.0
  (4222, 2709)	1.0
  (4222, 6926)	1.0
  (4223, 117)	1.0
  (4223, 6124)	1.0
  (4224, 326)	1.0
  (4224, 4455)	1.0
  (4225, 1597)	1.0
  (4225, 5920)	1.0
  (4226, 111)	1.0
  (4226, 5998)	1.0
  (4227, 1233)	1.0
  (4227, 5905)	1.0
  (4228, 1266)	1.0
  (4228, 4437)	1.0
  (4229, 1751)	1.0
  (4229, 4744)	1.0
  (4230, 2057)	1.0
  (4230, 5591)	1.0
(4231, 8428)


In [12]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.3, random_state=17)
print(X_train.shape)
print(Y_train.shape)
print(X_test.shape)
print(Y_test.shape)

(2961, 8428)
(2961, 1)
(1270, 8428)
(1270, 1)


In [13]:
NaiveBayes = MultinomialNB().fit(X_train,np.ravel(Y_train,order='C'))
print(NaiveBayes)

MultinomialNB()


In [14]:
prediction = NaiveBayes.predict(X_test)
accuracy = accuracy_score(Y_test, prediction)
print(prediction)
print(accuracy)

[1 1 1 ... 1 1 1]
0.8433070866141732


In [15]:
classifier = NaiveBayes

In [16]:
Y_predict = classifier.predict(X_test)
print(Y_predict)

[1 1 1 ... 1 1 1]


In [17]:
precision_score(Y_test, classifier.predict(X_test))

0.843183609141056

In [18]:
f1_score(Y_test, classifier.predict(X_test))

0.9149209063702436

In [19]:
#Prediksi

df_uji=pd.read_excel(r'D:\big data\data uji BDC.xlsx')
df_uji.head()

ID              tanggal  \
0  238057  2020-07-13 00:00:00   
1  238158  2020-07-06 00:00:00   
2  238865  2020-04-22 00:00:00   
3  248298  2019-10-22 00:00:00   
4  255176  2020-05-01 00:00:00   

                                               judul  \
0  Narasi Tito Karnavian Berideologi Komunis Kare...   
1  Anies: Seberat beratnya Pekerjaan Akan terasa ...   
2  Hindu di india Melemparkan Patung Buatan Merek...   
3  RSCM Praktekkan Penyedotan Plug  Vena/Saluran ...   
4             Permohonan Kelonggaran Angsuran ke OJK   

                                              narasi nama file gambar  
0  TITO KARNIVAN ITU BERIDIOLOGI KOMUNIS DIA BISA...       238057.jpg  
1  Seberat beratnya Pekerjaan Akan terasa ringan ...       238158.jpg  
2  Hindu di india melemparkan patung buatan merek...       238865.jpg  
3  Mulai Hari ini di RSCM mulai diPraktekkan Peny...       248298.jpg  
4  Untuk sekedar info, Bagi anda yg punya ansuran...       255176.jpg

In [20]:
df_uji = df_uji.drop("tanggal", axis=1)
df_uji = df_uji.drop("nama file gambar", axis=1)
df_uji

ID                                              judul  \
0    238057  Narasi Tito Karnavian Berideologi Komunis Kare...   
1    238158  Anies: Seberat beratnya Pekerjaan Akan terasa ...   
2    238865  Hindu di india Melemparkan Patung Buatan Merek...   
3    248298  RSCM Praktekkan Penyedotan Plug  Vena/Saluran ...   
4    255176             Permohonan Kelonggaran Angsuran ke OJK   
..      ...                                                ...   
465  206021  Dijemput oleh Tim Medis, Kakak Beradik Usia 8 ...   
466  219874  : Pertanda Alam, Kera Putih Mulai Turun Dari G...   
467  222802  Pasar Wameo dan Karya Nugraha di Tutup selama ...   
468  226020  Klarifikasi KPK Terkait Foto Setya Novanto Tan...   
469  232887        Erdogan Tidak Pernah Akui Kemenangan Jokowi   

                                                narasi  
0    TITO KARNIVAN ITU BERIDIOLOGI KOMUNIS DIA BISA...  
1    Seberat beratnya Pekerjaan Akan terasa ringan ...  
2    Hindu di india melemparkan patung buatan merek...  
3    Mulai Hari ini di RSCM mulai diPraktekkan Peny...  
4    Untuk sekedar info, Bagi anda yg punya ansuran...  
..                                                 ...  
465  DiTangerang, dua bersaudara kakak beradik usia...  
466  Pertanda Alam, Kera Putih Mulai Turun Dari Gun...  
467  Assalamu Alaikum …\n \n  Info dari pedagang pa...  
468  Secara tidak sengaja sekitar pukul 06.00 WIB d...  
469  Artikel dalam laman daring aljazera.online ber...  

[470 rows x 3 columns]

In [21]:
Xlatih2 = df_uji.drop("ID", axis=1)
print(Xlatih2)

                                                 judul  \
0    Narasi Tito Karnavian Berideologi Komunis Kare...   
1    Anies: Seberat beratnya Pekerjaan Akan terasa ...   
2    Hindu di india Melemparkan Patung Buatan Merek...   
3    RSCM Praktekkan Penyedotan Plug  Vena/Saluran ...   
4               Permohonan Kelonggaran Angsuran ke OJK   
..                                                 ...   
465  Dijemput oleh Tim Medis, Kakak Beradik Usia 8 ...   
466  : Pertanda Alam, Kera Putih Mulai Turun Dari G...   
467  Pasar Wameo dan Karya Nugraha di Tutup selama ...   
468  Klarifikasi KPK Terkait Foto Setya Novanto Tan...   
469        Erdogan Tidak Pernah Akui Kemenangan Jokowi   

                                                narasi  
0    TITO KARNIVAN ITU BERIDIOLOGI KOMUNIS DIA BISA...  
1    Seberat beratnya Pekerjaan Akan terasa ringan ...  
2    Hindu di india melemparkan patung buatan merek...  
3    Mulai Hari ini di RSCM mulai diPraktekkan Peny...  
4    Untuk sekedar

In [25]:
tfidf_transformer = OneHotEncoder()
A = tfidf_transformer.fit_transform(Xlatih2)
print(A)
print(A.shape)

  (0, 259)	1.0
  (0, 865)	1.0
  (1, 40)	1.0
  (1, 825)	1.0
  (2, 160)	1.0
  (2, 622)	1.0
  (3, 331)	1.0
  (3, 741)	1.0
  (4, 306)	1.0
  (4, 888)	1.0
  (5, 27)	1.0
  (5, 513)	1.0
  (6, 364)	1.0
  (6, 721)	1.0
  (7, 313)	1.0
  (7, 707)	1.0
  (8, 288)	1.0
  (8, 754)	1.0
  (9, 88)	1.0
  (9, 527)	1.0
  (10, 70)	1.0
  (10, 730)	1.0
  (11, 251)	1.0
  (11, 592)	1.0
  (12, 340)	1.0
  :	:
  (457, 783)	1.0
  (458, 156)	1.0
  (458, 555)	1.0
  (459, 131)	1.0
  (459, 801)	1.0
  (460, 394)	1.0
  (460, 879)	1.0
  (461, 126)	1.0
  (461, 838)	1.0
  (462, 332)	1.0
  (462, 687)	1.0
  (463, 234)	1.0
  (463, 657)	1.0
  (464, 115)	1.0
  (464, 600)	1.0
  (465, 95)	1.0
  (465, 579)	1.0
  (466, 16)	1.0
  (466, 791)	1.0
  (467, 282)	1.0
  (467, 511)	1.0
  (468, 218)	1.0
  (468, 829)	1.0
  (469, 109)	1.0
  (469, 510)	1.0
(470, 939)


In [26]:
prediction = NaiveBayes.predict(A)
print(prediction)

ValueError: dimension mismatch