In [201]:
import pandas as pd
import numpy as np

In [202]:
df = pd.read_excel('E:\BDC\Data Latih BDC.xlsx')

In [203]:
df.head()

ID  label              tanggal  \
0   71      1  2020-08-17 00:00:00   
1  461      1  2020-07-17 00:00:00   
2  495      1  2020-07-13 00:00:00   
3  550      1  2020-07-08 00:00:00   
4  681      1  2020-06-24 00:00:00   

                                               judul  \
0  Pemakaian Masker Menyebabkan Penyakit Legionna...   
1  Instruksi Gubernur Jateng tentang penilangan  ...   
2  Foto Jim Rohn: Jokowi adalah presiden terbaik ...   
3  ini bukan politik, tapi kenyataan Pak Jokowi b...   
4       Foto Kadrun kalo lihat foto ini panas dingin   

                                              narasi nama file gambar  
0  A caller to a radio talk show recently shared ...           71.jpg  
1  Yth.Seluruh Anggota Grup Sesuai Instruksi Gube...          461.png  
2  Jokowi adalah presiden terbaik dlm sejarah ban...          495.png  
3  Maaf Mas2 dan Mbak2, ini bukan politik, tapi k...          550.png  
4        Kadrun kalo lihat foto ini panas dingin . .          681.jpg

In [204]:
df = df.drop("tanggal", axis=1)

In [205]:
df = df.drop("ID", axis=1)

In [206]:
df = df.drop("nama file gambar", axis=1)

In [207]:
df

label                                              judul  \
0         1  Pemakaian Masker Menyebabkan Penyakit Legionna...   
1         1  Instruksi Gubernur Jateng tentang penilangan  ...   
2         1  Foto Jim Rohn: Jokowi adalah presiden terbaik ...   
3         1  ini bukan politik, tapi kenyataan Pak Jokowi b...   
4         1       Foto Kadrun kalo lihat foto ini panas dingin   
...     ...                                                ...   
4226      1  : KPK Dilarang Membawa Brimob Bersenjata Masuk...   
4227      1            Foto pejabat keuangan dibawah palu arit   
4228      1  Gambar Denny Siregar Musuh Warga Tasikmalaya d...   
4229      1  Kaesang: Bapak Saya dengan Kesederhaan Bisa Ni...   
4230      1  Laser dari termometer gun akan merusak struktu...   

                                                 narasi  
0     A caller to a radio talk show recently shared ...  
1     Yth.Seluruh Anggota Grup Sesuai Instruksi Gube...  
2     Jokowi adalah presiden terbaik dlm sejarah ban...  
3     Maaf Mas2 dan Mbak2, ini bukan politik, tapi k...  
4           Kadrun kalo lihat foto ini panas dingin . .  
...                                                 ...  
4226  KPK Dilarang Membawa Brimob Bersenjata Masuk G...  
4227  Jangan mau dialihkan kepada pakaian adat… FOKU...  
4228                 Akhir nya bisa terkenal bang denny  
4229  Bapak Saya dengan Kesederhaan Bisa Nipu Rakyat...  
4230  IN: Saya nolak. Kalau Anda mau periksa, bukan ...  

[4231 rows x 3 columns]

In [208]:
df = df[0:4231]

In [209]:
df

label                                              judul  \
0         1  Pemakaian Masker Menyebabkan Penyakit Legionna...   
1         1  Instruksi Gubernur Jateng tentang penilangan  ...   
2         1  Foto Jim Rohn: Jokowi adalah presiden terbaik ...   
3         1  ini bukan politik, tapi kenyataan Pak Jokowi b...   
4         1       Foto Kadrun kalo lihat foto ini panas dingin   
...     ...                                                ...   
4226      1  : KPK Dilarang Membawa Brimob Bersenjata Masuk...   
4227      1            Foto pejabat keuangan dibawah palu arit   
4228      1  Gambar Denny Siregar Musuh Warga Tasikmalaya d...   
4229      1  Kaesang: Bapak Saya dengan Kesederhaan Bisa Ni...   
4230      1  Laser dari termometer gun akan merusak struktu...   

                                                 narasi  
0     A caller to a radio talk show recently shared ...  
1     Yth.Seluruh Anggota Grup Sesuai Instruksi Gube...  
2     Jokowi adalah presiden terbaik dlm sejarah ban...  
3     Maaf Mas2 dan Mbak2, ini bukan politik, tapi k...  
4           Kadrun kalo lihat foto ini panas dingin . .  
...                                                 ...  
4226  KPK Dilarang Membawa Brimob Bersenjata Masuk G...  
4227  Jangan mau dialihkan kepada pakaian adat… FOKU...  
4228                 Akhir nya bisa terkenal bang denny  
4229  Bapak Saya dengan Kesederhaan Bisa Nipu Rakyat...  
4230  IN: Saya nolak. Kalau Anda mau periksa, bukan ...  

[4231 rows x 3 columns]

In [210]:
Y = df.iloc[:,:-2].values

In [211]:
Y[0]

array([1], dtype=int64)

In [212]:
X = df.loc[:, 'judul':'narasi'].values

In [213]:
X[1]

array(['Instruksi Gubernur Jateng tentang penilangan  bagi yg tidak bermasker di muka umum Rp.150.000 menggunakan e-tilang Via apps PIKOBAR',
       'Yth.Seluruh Anggota Grup Sesuai Instruksi Gubernur Jawa Tengah Hasil Rapat Tim Gugus Tugas Covid 19 Jateng sbb:'],
      dtype=object)

In [214]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features=5000)
mat_body = cv.fit_transform(X[:,1]).todense()

In [215]:
mat_body

matrix([[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [216]:
cv_head = CountVectorizer(max_features=5000)
mat_head = cv_head.fit_transform(X[:,0]).todense()

In [217]:
mat_head

matrix([[0, 0, 0, ..., 0, 0, 0],
        [0, 1, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [218]:
X_mat = np.hstack((mat_head, mat_body))

In [244]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X_mat, Y, test_size=0.2, random_state=0)

In [245]:
from sklearn.tree import DecisionTreeClassifier
dtc = DecisionTreeClassifier(criterion='entropy')
dtc.fit(X_train, Y_train)
Y_pred= dtc.predict(X_test)

In [246]:
from sklearn.metrics import confusion_matrix
confusion_matrix(Y_test, Y_pred)

array([[ 65,  94],
       [ 59, 629]], dtype=int64)

In [248]:
(65+629)/(65+629+94+59)

0.8193624557260921