In [1]:
import pandas as pd
import numpy as np

from sklearn.feature_extraction.text import CountVectorizer
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import MultinomialNB

from sklearn.metrics import recall_score
from sklearn.metrics import precision_score
from sklearn.metrics import f1_score

In [2]:
df_latih = pd.read_excel(r'D:\big data\Data Latih BDC.xlsx')

In [3]:
df_latih.tail()

ID  label              tanggal  \
4226  999287      1  2016-01-17 00:00:00   
4227  999472      1  2020-08-20 00:00:00   
4228  999501      1  2020-08-17 00:00:00   
4229  999848      1  2020-07-21 00:00:00   
4230  999860      1  2020-07-20 00:00:00   

                                                  judul  \
4226  : KPK Dilarang Membawa Brimob Bersenjata Masuk...   
4227            Foto pejabat keuangan dibawah palu arit   
4228  Gambar Denny Siregar Musuh Warga Tasikmalaya d...   
4229  Kaesang: Bapak Saya dengan Kesederhaan Bisa Ni...   
4230  Laser dari termometer gun akan merusak struktu...   

                                                 narasi nama file gambar  
4226  KPK Dilarang Membawa Brimob Bersenjata Masuk G...       999287.jpg  
4227  Jangan mau dialihkan kepada pakaian adat… FOKU...       999472.png  
4228                 Akhir nya bisa terkenal bang denny       999501.jpg  
4229  Bapak Saya dengan Kesederhaan Bisa Nipu Rakyat...       999848.jpg  
4230  IN: Saya nolak. Kalau Anda mau periksa, bukan ...       999860.png

In [4]:
df_latih = df_latih.drop("tanggal", axis=1)
df_latih = df_latih.drop("nama file gambar", axis=1)
df_latih = df_latih.drop("ID", axis=1)
df_latih

label                                              judul  \
0         1  Pemakaian Masker Menyebabkan Penyakit Legionna...   
1         1  Instruksi Gubernur Jateng tentang penilangan  ...   
2         1  Foto Jim Rohn: Jokowi adalah presiden terbaik ...   
3         1  ini bukan politik, tapi kenyataan Pak Jokowi b...   
4         1       Foto Kadrun kalo lihat foto ini panas dingin   
...     ...                                                ...   
4226      1  : KPK Dilarang Membawa Brimob Bersenjata Masuk...   
4227      1            Foto pejabat keuangan dibawah palu arit   
4228      1  Gambar Denny Siregar Musuh Warga Tasikmalaya d...   
4229      1  Kaesang: Bapak Saya dengan Kesederhaan Bisa Ni...   
4230      1  Laser dari termometer gun akan merusak struktu...   

                                                 narasi  
0     A caller to a radio talk show recently shared ...  
1     Yth.Seluruh Anggota Grup Sesuai Instruksi Gube...  
2     Jokowi adalah presiden terbaik dlm sejarah ban...  
3     Maaf Mas2 dan Mbak2, ini bukan politik, tapi k...  
4           Kadrun kalo lihat foto ini panas dingin . .  
...                                                 ...  
4226  KPK Dilarang Membawa Brimob Bersenjata Masuk G...  
4227  Jangan mau dialihkan kepada pakaian adat… FOKU...  
4228                 Akhir nya bisa terkenal bang denny  
4229  Bapak Saya dengan Kesederhaan Bisa Nipu Rakyat...  
4230  IN: Saya nolak. Kalau Anda mau periksa, bukan ...  

[4231 rows x 3 columns]

In [5]:
df_latih.shape

(4231, 3)

In [6]:
df_latih.sort_inplace=True

In [7]:
df_latih.head(3506)

label                                              judul  \
0         1  Pemakaian Masker Menyebabkan Penyakit Legionna...   
1         1  Instruksi Gubernur Jateng tentang penilangan  ...   
2         1  Foto Jim Rohn: Jokowi adalah presiden terbaik ...   
3         1  ini bukan politik, tapi kenyataan Pak Jokowi b...   
4         1       Foto Kadrun kalo lihat foto ini panas dingin   
...     ...                                                ...   
3501      1   Ya robb jangan biarkan kecurangan terjadi Aamiin   
3502      1                     Soal Tes CPNS 2018 Telah Bocor   
3503      1            Wali Kota Palu Meninggal Karena Tsunami   
3504      1         MINUMAN RED BULL MENGANDUNG SPERMA BANTENG   
3505      0  Klarifikasi BMKG Terkait Foto Indonesia Very H...   

                                                 narasi  
0     A caller to a radio talk show recently shared ...  
1     Yth.Seluruh Anggota Grup Sesuai Instruksi Gube...  
2     Jokowi adalah presiden terbaik dlm sejarah ban...  
3     Maaf Mas2 dan Mbak2, ini bukan politik, tapi k...  
4           Kadrun kalo lihat foto ini panas dingin . .  
...                                                 ...  
3501   Ya robb jangan biarkan kecurangan terjadi Aamiin  
3502  Ternyata Soal TIU CPNS 2018 Telah Bocor, Ayo P...  
3503  Innalilahi wa innailaihi rojiun\n walikota pal...  
3504  Energy drinks such as Red Bull have long been ...  
3505  Bencana biasa saja bukan Nasional tapi minta b...  

[3506 rows x 3 columns]

In [8]:
vectorizer = CountVectorizer(stop_words='english')

In [9]:
all_features = vectorizer.fit_transform(df_latih.narasi)

In [10]:
print(all_features)

  (0, 2985)	1
  (0, 14121)	1
  (0, 16551)	1
  (0, 14275)	1
  (0, 15625)	1
  (0, 18156)	1
  (0, 6421)	1
  (0, 17371)	1
  (0, 3430)	2
  (0, 3423)	1
  (0, 3642)	2
  (0, 9131)	1
  (0, 9329)	1
  (0, 4862)	1
  (0, 5531)	1
  (0, 16254)	1
  (0, 17154)	1
  (0, 9140)	2
  (0, 4571)	2
  (0, 18222)	1
  (0, 9773)	3
  (0, 3638)	2
  (0, 9363)	1
  (0, 17591)	1
  (0, 11322)	1
  :	:
  (4230, 4712)	1
  (4230, 8128)	2
  (4230, 5813)	1
  (4230, 7335)	2
  (4230, 17115)	1
  (4230, 16198)	1
  (4230, 775)	2
  (4230, 7409)	2
  (4230, 7710)	1
  (4230, 12202)	1
  (4230, 3945)	1
  (4230, 13274)	3
  (4230, 14004)	1
  (4230, 8213)	1
  (4230, 10171)	2
  (4230, 16734)	1
  (4230, 11898)	1
  (4230, 6106)	1
  (4230, 17039)	1
  (4230, 9063)	1
  (4230, 9062)	2
  (4230, 11031)	1
  (4230, 16788)	1
  (4230, 7752)	1
  (4230, 8841)	1


In [11]:
all_features.shape

(4231, 18481)

In [12]:
vectorizer.vocabulary_

{'caller': 2985,
 'radio': 14121,
 'talk': 16551,
 'recently': 14275,
 'shared': 15625,
 'wife': 18156,
 'hospitalized': 6421,
 'told': 17371,
 'covid': 3430,
 'couple': 3423,
 'days': 3642,
 'left': 9131,
 'live': 9329,
 'doctor': 4862,
 'friend': 5531,
 'suggested': 16254,
 'tested': 17154,
 'legionnaires': 9140,
 'disease': 4571,
 'wore': 18222,
 'mask': 9773,
 'day': 3638,
 'long': 9363,
 'turns': 17591,
 'moisture': 11322,
 'bacteria': 1423,
 'given': 5829,
 'antibiotics': 1044,
 'better': 2413,
 'spikes': 16073,
 'really': 14264,
 'induced': 6726,
 'infections': 6738,
 'yth': 18355,
 'seluruh': 15356,
 'anggota': 977,
 'grup': 5934,
 'sesuai': 15557,
 'instruksi': 6844,
 'gubernur': 5941,
 'jawa': 7163,
 'tengah': 16802,
 'hasil': 6184,
 'rapat': 14205,
 'tim': 17247,
 'gugus': 5953,
 'tugas': 17526,
 '19': 112,
 'jateng': 7151,
 'sbb': 15034,
 'jokowi': 7307,
 'adalah': 517,
 'presiden': 13845,
 'terbaik': 16862,
 'dlm': 4845,
 'sejarah': 15232,
 'bangsa': 1580,
 'indonesia': 67

In [13]:
Y = df_latih.iloc[:,:-2].values

In [14]:
X = df_latih.loc[:, 'judul':'narasi'].values

In [15]:
X.ndim

2

In [16]:
print(X)
X_1d = X.flatten()
print(X_1d)

[['Pemakaian Masker Menyebabkan Penyakit Legionnaires'
  'A caller to a radio talk show recently shared that his wife was hospitalized n told she had COVID n only a couple of days left to live . A doctor friend suggested she be tested for legionnaires disease because she wore the same mask every day all day long . Turns out it WAS legionnaires disease from the moisture n bacteria in her mask . She was given antibiotics n within two days was better . WHAT IF these ‘spikes’ in COVID are really something else due to ‘mask induced infections’ .??🤔🤔🤔']
 ['Instruksi Gubernur Jateng tentang penilangan  bagi yg tidak bermasker di muka umum Rp.150.000 menggunakan e-tilang Via apps PIKOBAR'
  'Yth.Seluruh Anggota Grup Sesuai Instruksi Gubernur Jawa Tengah Hasil Rapat Tim Gugus Tugas Covid 19 Jateng sbb:']
 ['Foto Jim Rohn: Jokowi adalah presiden terbaik dlm sejarah bangsa Indonesia'
  'Jokowi adalah presiden terbaik dlm sejarah bangsa Indonesia. Jim Rohn, motivator terbaik dunia']
 ...
 ['Gambar

In [17]:
X_1d.ndim

1

In [18]:
listToStr = ' '.join([str(elem) for elem in X]) 
kalimat = listToStr
case_folding = kalimat.lower()
print(case_folding)

['pemakaian masker menyebabkan penyakit legionnaires'
 'a caller to a radio talk show recently shared that his wife was hospitalized n told she had covid n only a couple of days left to live . a doctor friend suggested she be tested for legionnaires disease because she wore the same mask every day all day long . turns out it was legionnaires disease from the moisture n bacteria in her mask . she was given antibiotics n within two days was better . what if these ‘spikes’ in covid are really something else due to ‘mask induced infections’ .??🤔🤔🤔'] ['instruksi gubernur jateng tentang penilangan  bagi yg tidak bermasker di muka umum rp.150.000 menggunakan e-tilang via apps pikobar'
 'yth.seluruh anggota grup sesuai instruksi gubernur jawa tengah hasil rapat tim gugus tugas covid 19 jateng sbb:'] ['foto jim rohn: jokowi adalah presiden terbaik dlm sejarah bangsa indonesia'
 'jokowi adalah presiden terbaik dlm sejarah bangsa indonesia. jim rohn, motivator terbaik dunia'] ['ini bukan politik,

In [19]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features=5000)
mat_body = cv.fit_transform(X[:,1]).todense()

In [20]:
mat_body

matrix([[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [21]:
cv_head = CountVectorizer(max_features=5000)
mat_head = cv_head.fit_transform(X[:,0]).todense()

In [22]:
mat_head

matrix([[0, 0, 0, ..., 0, 0, 0],
        [0, 1, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [23]:
X_mat = np.hstack((mat_head, mat_body))

In [24]:
X_mat

matrix([[0, 0, 0, ..., 0, 0, 0],
        [0, 1, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [25]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(all_features, df_latih.label, test_size=0.3, random_state=88)

In [26]:
X_train.shape 

(2961, 18481)

In [27]:
print(X_train)

  (0, 517)	2
  (0, 3576)	2
  (0, 6787)	1
  (0, 3820)	1
  (0, 7723)	1
  (0, 6989)	3
  (0, 2522)	1
  (0, 12089)	1
  (0, 6431)	1
  (0, 18326)	2
  (0, 17779)	1
  (0, 7612)	1
  (0, 12153)	1
  (0, 6166)	1
  (0, 8440)	1
  (0, 15483)	1
  (0, 11585)	1
  (0, 16691)	2
  (0, 7164)	1
  (0, 7085)	1
  (0, 6380)	1
  (0, 6521)	1
  (0, 16761)	1
  (0, 1669)	1
  (0, 3620)	1
  :	:
  (2960, 16326)	1
  (2960, 12575)	1
  (2960, 7479)	1
  (2960, 16872)	1
  (2960, 2472)	1
  (2960, 2098)	1
  (2960, 17520)	1
  (2960, 1439)	1
  (2960, 14159)	1
  (2960, 11889)	1
  (2960, 14782)	1
  (2960, 7345)	1
  (2960, 17990)	1
  (2960, 14984)	1
  (2960, 15484)	1
  (2960, 18407)	1
  (2960, 3399)	1
  (2960, 12782)	1
  (2960, 11213)	1
  (2960, 947)	1
  (2960, 18348)	1
  (2960, 16602)	1
  (2960, 14772)	1
  (2960, 7908)	1
  (2960, 772)	1


In [28]:
print(Y_train)

2670    1
1697    1
1445    1
2488    1
612     1
       ..
1598    1
362     1
2481    1
4047    1
2008    1
Name: label, Length: 2961, dtype: int64


In [29]:
X_test.shape

(1270, 18481)

In [30]:
classifier = MultinomialNB()

In [31]:
classifier.fit(X_train, Y_train)

MultinomialNB()

In [62]:
Y_predict = classifier.predict(X_test)

In [65]:
Y_predict.shape

(1270,)

In [56]:
nr_correct = (Y_test == classifier.predict(X_test)).sum()

In [33]:
nr_incorrect = Y_test.size - nr_correct

In [34]:
recall_score(Y_test, classifier.predict(X_test))

0.9060402684563759

In [35]:
precision_score(Y_test, classifier.predict(X_test))

0.84

In [36]:
f1_score(Y_test, classifier.predict(X_test))

0.8717712177121771

In [41]:
#classifier baru
from sklearn.naive_bayes import GaussianNB
modelnb = GaussianNB()

In [42]:
A = X_train
A.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 1, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [43]:
Ylatih = Y_train.values
B=Ylatih
C=B.transpose()
print(C)

[1 1 1 ... 1 1 1]


In [44]:
#Masukin data training
nbtrain = modelnb.fit(A, B)

TypeError: A sparse matrix was passed, but dense data is required. Use X.toarray() to convert to a dense numpy array.

In [45]:
#Prediksi
import numpy as np


dfuji=pd.read_excel(r'D:\big data\data uji BDC.xlsx')
dfuji.head()

ID              tanggal  \
0  238057  2020-07-13 00:00:00   
1  238158  2020-07-06 00:00:00   
2  238865  2020-04-22 00:00:00   
3  248298  2019-10-22 00:00:00   
4  255176  2020-05-01 00:00:00   

                                               judul  \
0  Narasi Tito Karnavian Berideologi Komunis Kare...   
1  Anies: Seberat beratnya Pekerjaan Akan terasa ...   
2  Hindu di india Melemparkan Patung Buatan Merek...   
3  RSCM Praktekkan Penyedotan Plug  Vena/Saluran ...   
4             Permohonan Kelonggaran Angsuran ke OJK   

                                              narasi nama file gambar  
0  TITO KARNIVAN ITU BERIDIOLOGI KOMUNIS DIA BISA...       238057.jpg  
1  Seberat beratnya Pekerjaan Akan terasa ringan ...       238158.jpg  
2  Hindu di india melemparkan patung buatan merek...       238865.jpg  
3  Mulai Hari ini di RSCM mulai diPraktekkan Peny...       248298.jpg  
4  Untuk sekedar info, Bagi anda yg punya ansuran...       255176.jpg

In [46]:
df_uji = dfuji.drop("tanggal", axis=1)
df_uji = dfuji.drop("ID", axis=1)
df_uji = dfuji.drop("nama file gambar", axis=1)
df_uji

ID              tanggal  \
0    238057  2020-07-13 00:00:00   
1    238158  2020-07-06 00:00:00   
2    238865  2020-04-22 00:00:00   
3    248298  2019-10-22 00:00:00   
4    255176  2020-05-01 00:00:00   
..      ...                  ...   
465  206021  2020-05-01 00:00:00   
466  219874  2017-10-02 00:00:00   
467  222802  2020-03-22 00:00:00   
468  226020  2018-09-25 00:00:00   
469  232887  2019-04-25 00:00:00   

                                                 judul  \
0    Narasi Tito Karnavian Berideologi Komunis Kare...   
1    Anies: Seberat beratnya Pekerjaan Akan terasa ...   
2    Hindu di india Melemparkan Patung Buatan Merek...   
3    RSCM Praktekkan Penyedotan Plug  Vena/Saluran ...   
4               Permohonan Kelonggaran Angsuran ke OJK   
..                                                 ...   
465  Dijemput oleh Tim Medis, Kakak Beradik Usia 8 ...   
466  : Pertanda Alam, Kera Putih Mulai Turun Dari G...   
467  Pasar Wameo dan Karya Nugraha di Tutup selama ...   
468  Klarifikasi KPK Terkait Foto Setya Novanto Tan...   
469        Erdogan Tidak Pernah Akui Kemenangan Jokowi   

                                                narasi  
0    TITO KARNIVAN ITU BERIDIOLOGI KOMUNIS DIA BISA...  
1    Seberat beratnya Pekerjaan Akan terasa ringan ...  
2    Hindu di india melemparkan patung buatan merek...  
3    Mulai Hari ini di RSCM mulai diPraktekkan Peny...  
4    Untuk sekedar info, Bagi anda yg punya ansuran...  
..                                                 ...  
465  DiTangerang, dua bersaudara kakak beradik usia...  
466  Pertanda Alam, Kera Putih Mulai Turun Dari Gun...  
467  Assalamu Alaikum …\n \n  Info dari pedagang pa...  
468  Secara tidak sengaja sekitar pukul 06.00 WIB d...  
469  Artikel dalam laman daring aljazera.online ber...  

[470 rows x 4 columns]

In [47]:
vectorizer = CountVectorizer(stop_words='english')


In [50]:
X_testbaru = vectorizer.fit_transform(df_uji.narasi)
print(X_testbaru)

  (0, 4240)	1
  (0, 1812)	1
  (0, 1633)	1
  (0, 513)	1
  (0, 2048)	2
  (0, 932)	1
  (0, 621)	1
  (0, 931)	4
  (0, 1828)	1
  (0, 3310)	1
  (0, 1807)	1
  (0, 3246)	1
  (0, 3722)	1
  (0, 2930)	1
  (0, 3012)	1
  (0, 779)	1
  (0, 352)	1
  (1, 931)	1
  (1, 3674)	1
  (1, 476)	1
  (1, 3054)	1
  (1, 152)	1
  (1, 4111)	1
  (1, 3525)	1
  (1, 609)	1
  :	:
  (469, 4307)	2
  (469, 306)	1
  (469, 880)	1
  (469, 1253)	2
  (469, 170)	1
  (469, 1922)	3
  (469, 278)	1
  (469, 3983)	1
  (469, 3020)	1
  (469, 4105)	1
  (469, 3707)	1
  (469, 3)	1
  (469, 1727)	1
  (469, 4459)	1
  (469, 2888)	1
  (469, 2147)	1
  (469, 190)	1
  (469, 528)	1
  (469, 2447)	1
  (469, 3185)	1
  (469, 3477)	1
  (469, 4063)	1
  (469, 4362)	1
  (469, 490)	1
  (469, 1492)	1


In [54]:
X_testbaru.shape

(470, 4518)

In [104]:
vectorizer.vocabulary_

{'tito': 4240,
 'karnivan': 1812,
 'itu': 1633,
 'beridiologi': 513,
 'komunis': 2048,
 'dia': 932,
 'bisa': 621,
 'di': 931,
 'katakan': 1828,
 'pki': 3310,
 'karena': 1807,
 'pernah': 3246,
 'sekolahlah': 3722,
 'oleh': 2930,
 'partai': 3012,
 'china': 779,
 'baijing': 352,
 'seberat': 3674,
 'beratnya': 476,
 'pekerjaan': 3054,
 'akan': 152,
 'terasa': 4111,
 'ringan': 3525,
 'bila': 609,
 'tidak': 4221,
 'kerjakan': 1957,
 'hindu': 1488,
 'india': 1568,
 'melemparkan': 2395,
 'patung': 3032,
 'buatan': 691,
 'mereka': 2681,
 'ke': 1838,
 'laut': 2169,
 'apa': 248,
 'yang': 4492,
 'lakukan': 2142,
 'dapat': 875,
 'membela': 2441,
 'dari': 879,
 'virus': 4392,
 'corona': 827,
 'maha': 2261,
 'suci': 3950,
 'allah': 191,
 'tuhan': 4290,
 'semesta': 3757,
 'alam': 176,
 'mulai': 2778,
 'hari': 1454,
 'ini': 1585,
 'rscm': 3554,
 'dipraktekkan': 1092,
 'penyedotan': 3195,
 'plug': 3320,
 'sumbatan': 3964,
 'vena': 4385,
 'saluran': 3599,
 'darah': 878,
 'jantung': 1671,
 'jadi': 1643,
 

In [105]:
Y_prediksi = knn.predict(X_testbaru)

ValueError: Incompatible dimension for X and Y matrices: X.shape[1] == 4518 while Y.shape[1] == 18481